apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: 3ifp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: ssssooooso/gcu8s:v1 #여기에 도커허브에서 가져올 이미지 작성
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: 3ifp
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
