apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: 3ifp
type: Opaque
stringData:
  postgres-user: moon 
  postgres-password: "1234"
  database-url: postgresql://moon:1234@postgres:5432/moon

